In [5]:
import sys
sys.path.append("../data")
from pathlib import Path
import pandas as pd
from datasets_const import NUMERICAL_DATA_NAMES, CATEGORICAL_DATA_NAMES, GRAPH_DATA_NAMES, CV_DATA_NAMES, NLP_DATA_NAMES, TIMESERIES_DATA_NAMES
from data_getter import get_npz_dataset, get_categorical_dataset, get_glocalkd_dataset, get_time_series

%load_ext autoreload

%autoreload 2

ImportError: cannot import name 'get_time_series' from 'data_getter' (d:\AI_y3_s1\ProblemClasses\Isolation-Similarity-Forest\notebooks\../data\data_getter.py)

In [2]:
datasets_description = []

In [3]:
def append_desc(path, f, type_):
    data = f(path)
    X, y, name = data["X"], data["y"], data["name"]

    datasets_description.append({
        "name": name,
        "n_instances": X.shape[0],
        "n_features": X.shape[1],
        "outlier_ratio": f"{(y == 1).sum() * 100 / len(y):.2f}%",
        "type": type_
    })

### Numerical

In [4]:
NUMERICAL_ROOT = Path("../data/numerical")

for path in NUMERICAL_DATA_NAMES:
    path = NUMERICAL_ROOT / path
    append_desc(path, get_npz_dataset, "numerical")

CATEGORICAL

In [5]:
CATEGORICAL_ROOT = Path("../data/categorical")

for path in CATEGORICAL_DATA_NAMES:
    path = CATEGORICAL_ROOT / path
    append_desc(path, get_categorical_dataset, "categorical")

### GRAPH

In [6]:
GRAPH_PATH = "../data/graph/"
for name in GRAPH_DATA_NAMES:
    data = get_glocalkd_dataset(GRAPH_PATH, name, numerical_features=False)
    X, y, name = data["X"], data["y"], data["name"]

    datasets_description.append({
        "name": name,
        "n_instances": X.shape[0],
        "n_features": 1,
        "outlier_ratio": f"{(y == 1).sum() * 100 / len(y):.2f}%",
        "type": "graph"
    })

No node attributes
No node attributes
counts (array([0, 1]), array([7971,  433], dtype=int64))
No node attributes
No node attributes
counts (array([0, 1]), array([8116,  776], dtype=int64))
No node attributes
No node attributes
counts (array([0, 1]), array([6208, 1341], dtype=int64))
No node attributes
No node attributes
counts (array([0, 1]), array([8205,  234], dtype=int64))

### TIME SERIES

In [7]:
TIMESERIES_PATH = "../data/UnusualTimeSeries"
for name in TIMESERIES_DATA_NAMES:
    data = get_time_series(TIMESERIES_PATH, name)
    X, y, name = data["X"], data["y"], data["name"]

    datasets_description.append({
        "name": name,
        "n_instances": X.shape[0],
        "n_features": X.shape[1],
        "outlier_ratio": f"{(y == 1).sum() * 100 / len(y):.2f}%",
        "type": "timeseries"
    })

NLP and CV

In [8]:
NUMERICAL_ROOT = Path("../data/adBench/CV_by_ResNet18")

for path in CV_DATA_NAMES:
    path = NUMERICAL_ROOT / path
    append_desc(path, get_npz_dataset, "CV embedding")

In [9]:
NUMERICAL_ROOT = Path("../data/adBench/NLP_by_RoBERTa")

for path in NLP_DATA_NAMES:
    path = NUMERICAL_ROOT / path
    append_desc(path, get_npz_dataset, "NLP embedding")

#### Multiomics

In [88]:
X1 = pd.read_csv("../data/mixed/rosmap/X_1.csv", index_col=0)
X2 = pd.read_csv("../data/mixed/rosmap/X_2.csv", index_col=0)

In [90]:
pd.concat([X1, X2], axis=1).shape

(177, 400)

### Sequences of sets

### description

In [13]:
df = pd.DataFrame(datasets_description)

In [17]:
df

,name,n_instances,n_features,outlier_ratio,type
0,14_glass,214,7,4.21%,numerical
1,20_letter,1600,32,6.25%,numerical
2,21_Lymphography,148,18,4.05%,numerical
3,25_musk,3062,166,3.17%,numerical
4,26_optdigits,5216,64,2.88%,numerical
5,2_annthyroid,7200,6,7.42%,numerical
6,31_satimage-2,5803,36,1.22%,numerical
7,36_speech,3686,400,1.65%,numerical
8,38_thyroid,3772,6,2.47%,numerical
9,40_vowels,1456,12,3.43%,numerical
10,41_Waveform,3443,21,2.90%,numerical
11,42_WBC,223,9,4.48%,numerical
12,43_WDBC,367,30,2.72%,numerical
13,44_Wilt,4819,5,5.33%,numerical
14,6_cardio,1831,21,9.61%,numerical
15,ad_nominal,3263,1555,13.91%,categorical
16,AID362red_train_allpossiblenominal,4278,114,1.40%,categorical
17,apascal_entire_trainvsall,12694,64,1.39%,categorical
18,cmc-nominal,1472,8,1.97%,categorical
19,Reuters-corn-100,12896,100,1.84%,categorical
20,solar-flare_FvsAll-cleaned,1065,11,4.04%,categorical
21,HSE,8404,1,5.15%,graph
22,p53,8892,1,8.73%,graph
23,MMP,7549,1,17.76%,graph
24,PPAR-gamma,8439,1,2.77%,graph
25,Earthquakes,387,512,4.91%,timeseries
26,ECGFiveDays,465,136,4.95%,timeseries
27,MiddlePhalanxOutlineCorrect,583,80,4.97%,timeseries
28,SonyAIBORobotSurface1,367,70,4.90%,timeseries
29,TwoLeadECG,611,82,4.91%,timeseries
30,CIFAR10_0,5263,512,5.00%,CV embedding
31,FashionMNIST_0,6315,512,4.99%,CV embedding
32,SVHN_0,5208,512,4.99%,CV embedding
33,agnews_0,10000,768,5.00%,NLP embedding
34,amazon,10000,768,5.00%,NLP embedding
35,imdb,10000,768,5.00%,NLP embedding
36,yelp,10000,768,5.00%,NLP embedding